package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();
    private List<User> fakeUsersList = FAKE_USERS_RANDOM;

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier
        // create new random user to add:
        User randomUserToAdd = newRandomUser();
        // user added to the list
        users.add(randomUserToAdd);
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
        users.remove(user);
    }

    /**
     * Generate a random {@link User} from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list
     * */
    private User newRandomUser() {
        // create a random index:
        int randomFakeUserIndex = (int) (Math.random() * (fakeUsersList.size()));
        // get user with the random index from the list:
        User randomUserToAdd = fakeUsersList.get(randomFakeUserIndex);
        //return a user
        return randomUserToAdd;
    }
}
